name: Continuous Delivery
run-name: Tag new release
on:
  workflow_run:
    workflows:
      - Continuous Integration
    branches:
      - main
    types:
      - completed
jobs:
  push-tags:
    name: Push tags
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nix-cache
          key: ${{ runner.os }}-nix-${{ hashFiles('./flake.*') }}-golang-${{ hashFiles('./go.*') }}
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            cores = 0
            experimental-features = nix-command flakes
            keep-derivations = true
            keep-outputs = true
      - run: nix-store --import < /tmp/nix-cache
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          version=$(npm -j list setup-captain | jq -r .version)
          git tag "v$version"
          echo "newReleaseTag=v$version" >> $GITHUB_ENV

          if [[ $(echo $version | grep -v "-") ]]; then
            major=$(echo $version | awk -F '.' '{print $1}')
            git tag "v$major"

            minor=$(echo $version | awk -F '.' '{print $2}')
            git tag "v$major.$minor"
          fi

          git push --force --tags
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.newReleaseTag }}
          release_name: Release ${{ env.newReleaseTag }}
          draft: false
          prerelease: contains(env.newReleaseTag, "-")
